<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="120" started-at="2021-10-30T23:41:43Z" finished-at="2021-10-30T23:41:43Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="120" started-at="2021-10-30T23:41:43Z" finished-at="2021-10-30T23:41:43Z">
      <class name="practice.collections.codes.ExceptionTest">
        <test-method status="PASS" signature="FileNotFoundException()[pri:0, instance:practice.collections.codes.ExceptionTest@394df057]" name="FileNotFoundException" duration-ms="27" started-at="2021-10-30T23:41:43Z" finished-at="2021-10-30T23:41:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FileNotFoundException -->
        <test-method status="PASS" signature="NumberFormatException()[pri:0, instance:practice.collections.codes.ExceptionTest@394df057]" name="NumberFormatException" duration-ms="6" started-at="2021-10-30T23:41:43Z" finished-at="2021-10-30T23:41:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NumberFormatException -->
      </class> <!-- practice.collections.codes.ExceptionTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
